/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospitalidad;

import hospitalidad.Gestores.GestionAutobusesBD;
import hospitalidad.Gestores.GestionViajesBD;
import hospitalidad.beans.AutobusBean;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author vPalomo
 */
public class AutobusesMtto extends javax.swing.JPanel {

    
    private String idViaje;
    private Principal padre;
    private String modoVentana;
    private String idAutobus;
    
    public static final String nuevo = "NUEVO";
    public static final String mtto = "MTTO";
    
    /**
     * Creates new form AutobusesMtto
     */
    public AutobusesMtto() {
        initComponents();
    }

    public AutobusesMtto(String modoVentana, String filtroViaje, int selectedIndex, Principal padre, String idAutobus) {
        this.idViaje=filtroViaje;
        this.idAutobus=idAutobus;
        this.padre=padre;
        this.modoVentana=modoVentana;
        initComponents();
        jComboPeregrinaciones.setEnabled(false);
        jComboPeregrinaciones.setSelectedIndex(selectedIndex);
        prepararVentana();
    }

    private void prepararVentana(){
        if(AutobusesMtto.mtto.equals(this.modoVentana)){
            AutobusBean autobus=GestionAutobusesBD.getDatosAutobus(idAutobus);
            jTextDescripcion.setText(autobus.getDescripcion());
            jTextObservaciones.setText(autobus.getObservaciones());
            jTextEnfermos.setText(""+autobus.getPlazasEnfermos());
            jTextNoEnfermos.setText(""+autobus.getPlazasNoEnfermos());
        }else{
            jTextDescripcion.setText("");
            jTextObservaciones.setText("");
            jTextEnfermos.setText("");
            jTextNoEnfermos.setText("");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextEnfermos = new javax.swing.JTextField();
        jTextNoEnfermos = new javax.swing.JTextField();
        jTextObservaciones = new javax.swing.JTextField();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboPeregrinaciones = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Descripción:");

        jLabel2.setText("Observaciones:");

        jLabel3.setText("Plazas no efermos:");

        jLabel4.setText("Plazas para enfermos:");

        jLabel5.setText("Alta y modificación de autobuses");

        jLabel6.setText("Peregrinación:");

        jComboPeregrinaciones.setModel(GestionViajesBD.getModeloComboViajes());

        jButton1.setText("Cancelar/Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextDescripcion)
                            .addComponent(jTextObservaciones)
                            .addComponent(jTextNoEnfermos)
                            .addComponent(jTextEnfermos, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jComboPeregrinaciones, 0, 258, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel5)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboPeregrinaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNoEnfermos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextEnfermos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(AutobusesMtto.nuevo.equals(this.modoVentana)){
            if(altaAutobus()>=1){
                JOptionPane.showMessageDialog(this, "Autobus creado correctamente");
                AutobusBean autobus=new AutobusBean();
                jTextDescripcion.setText("");
                jTextObservaciones.setText("");
                jTextNoEnfermos.setText("");
                jTextEnfermos.setText("");
                padre.cargaTablaAutobuses();
            }else{
                JOptionPane.showMessageDialog(this, "Alguno de los datos no está soportado. Recuerde que el número de plazas deben ser datos numéricos");
            }
        }else{
            mttoAutobus();
            Window w = SwingUtilities.getWindowAncestor(this);
            w.setVisible(false);
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Cancelar o salir
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboPeregrinaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextEnfermos;
    private javax.swing.JTextField jTextNoEnfermos;
    private javax.swing.JTextField jTextObservaciones;
    // End of variables declaration//GEN-END:variables

    private int altaAutobus() {
        AutobusBean autobus=new AutobusBean();
        autobus.setDescripcion(jTextDescripcion.getText());
        autobus.setObservaciones(jTextObservaciones.getText());
        autobus.setPlazasNoEnfermos(Integer.parseInt(jTextNoEnfermos.getText()));
        autobus.setPlazasEnfermos(Integer.parseInt(jTextEnfermos.getText()));
        String filtroViaje = jComboPeregrinaciones.getModel().getElementAt(jComboPeregrinaciones.getSelectedIndex()).split(" - ")[0];
        autobus.setIdViaje(filtroViaje);
        return GestionAutobusesBD.setAutobus(autobus);
    }

    private void mttoAutobus() {
        AutobusBean autobus=new AutobusBean();
        autobus.setIdAutobus(idAutobus);
        autobus.setDescripcion(jTextDescripcion.getText());
        autobus.setObservaciones(jTextObservaciones.getText());
        autobus.setPlazasNoEnfermos(Integer.parseInt(jTextNoEnfermos.getText()));
        autobus.setPlazasEnfermos(Integer.parseInt(jTextEnfermos.getText()));
        String filtroViaje = jComboPeregrinaciones.getModel().getElementAt(jComboPeregrinaciones.getSelectedIndex()).split(" - ")[0];
        autobus.setIdViaje(filtroViaje);
        GestionAutobusesBD.updateAutobus(autobus);
    }
}
