/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospitalidad;

import hospitalidad.Gestores.GestionHabitacionesBD;
import hospitalidad.Gestores.GestionViajesBD;
import hospitalidad.beans.HabitacionBean;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author vPalomo
 */
public class HabitacionesMtto extends javax.swing.JPanel {

    
    private String idViaje;
    private Principal padre;
    private String modoVentana;
    private String idHabitacion;
    
    public static final String nuevo = "NUEVO";
    public static final String mtto = "MTTO";
    
    /**
     * 
     * @param idViaje
     * @param selectComboPeregrinaciones Indice de la opcion soleccionada en el combo de la ventana padre, para así seleccionar el mismo
     */
    public HabitacionesMtto(String modoVentana, String filtroViaje, int selectComboPeregrinaciones, Principal ventanaPadre, String idHabitacion) {
        this.modoVentana=modoVentana;
        this.padre=ventanaPadre;
        this.idViaje=idViaje;
        this.idHabitacion=idHabitacion;
        initComponents();
        jComboPeregrinaciones.setSelectedIndex(selectComboPeregrinaciones);
        prepararVentana();
    }

    private void prepararVentana(){
        if(HabitacionesMtto.mtto.equals(this.modoVentana)){
            HabitacionBean habitacion=GestionHabitacionesBD.getDatosHabitacion(idHabitacion);
            jTextCamas.setText(""+habitacion.getCamasTotales());
            jTextDesc1.setText(habitacion.getDescripcion1());
            jTextDesc2.setText(habitacion.getDescripcion2());
            jTextObser.setText(habitacion.getObservaciones());
        }else{
            jTextCamas.setText("");
            jTextDesc1.setText("");
            jTextDesc2.setText("");
            jTextObser.setText("");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextObser = new javax.swing.JTextField();
        jTextDesc2 = new javax.swing.JTextField();
        jTextDesc1 = new javax.swing.JTextField();
        jTextCamas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboPeregrinaciones = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboHoteles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Descripción 1:");

        jLabel2.setText("Descripción 2:");

        jLabel3.setText("Observaciones:");

        jLabel4.setText("Camas:");

        jTextCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCamasActionPerformed(evt);
            }
        });

        jLabel5.setText("Peregrinación:");

        jComboPeregrinaciones.setModel(GestionViajesBD.getModeloComboViajes());

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar/Salir");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Habitaciones - Alta y mantenimiento");

        jButton1.setText("Crear hotel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboHoteles.setModel(GestionHabitacionesBD.getModeloComboHoteles());

        jLabel7.setText("Hotel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(8, 8, 8)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboHoteles, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboPeregrinaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextDesc1)
                            .addComponent(jTextDesc2)
                            .addComponent(jTextObser)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCamas, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(235, 235, 235)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPeregrinaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextObser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCamasActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        //Guardar
        HabitacionBean habitacion=new HabitacionBean();
        habitacion.setDescripcion1(jTextDesc1.getText());
        habitacion.setDescripcion2(jTextDesc2.getText());
        habitacion.setObservaciones(jTextObser.getText());
        if("".equals(jTextCamas.getText())){
            JOptionPane.showMessageDialog(null, "Debe rellenar el número de camas");
            return;
        }
        habitacion.setCamasTotales(Integer.parseInt(jTextCamas.getText()));
        if(HabitacionesMtto.mtto.equals(this.modoVentana)){
            habitacion.setIdHabitacion(idHabitacion);
            GestionHabitacionesBD.setHabitacionMtto(habitacion);
            
            padre.cargaTablaHabitaciones();
            JOptionPane.showMessageDialog(null, "Habitación modificada correctamente");
            Window w = SwingUtilities.getWindowAncestor(this);
            w.setVisible(false);
            return;
        }else{
            
            if("".equals(habitacion.getDescripcion1())){
                JOptionPane.showMessageDialog(null, "Debe rellenar al menos la descripción 1");
                return;
            }else if(0==habitacion.getCamasTotales()){
                JOptionPane.showMessageDialog(null, "El número de camas no pueden ser 0");
                return;
            }
            String idViaje = jComboPeregrinaciones.getModel().getElementAt(jComboPeregrinaciones.getSelectedIndex()).split(" - ")[0];
            String idHotel = jComboHoteles.getModel().getElementAt(jComboHoteles.getSelectedIndex()).split(" - ")[0];
            habitacion.setIdHotel(idHotel);
            habitacion.setIdViaje(idViaje);
            GestionHabitacionesBD.setHabitacion(habitacion);
            prepararVentana();
            padre.cargaTablaHabitaciones();
            JOptionPane.showMessageDialog(null, "Habitación creada");
            //Window w = SwingUtilities.getWindowAncestor(this);
            //w.setVisible(false);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog frame = new JDialog((Frame) null, "Gestion de hoteles", true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        CrearHotel ventanaHotel=new CrearHotel();
        frame.getContentPane().add(ventanaHotel);
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
        if(CrearHotel.GUARDAR.equals(ventanaHotel.getOpcionBoton())){
            GestionHabitacionesBD.crearHotel(ventanaHotel.getTexto());
        }
        //iniciarMisComponentes();
        //frame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboHoteles;
    private javax.swing.JComboBox<String> jComboPeregrinaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextCamas;
    private javax.swing.JTextField jTextDesc1;
    private javax.swing.JTextField jTextDesc2;
    private javax.swing.JTextField jTextObser;
    // End of variables declaration//GEN-END:variables
}
