/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalidad;  

import hospitalidad.Gestores.GestionPersonasBD;
import hospitalidad.Gestores.GestionViajesBD;
import hospitalidad.beans.PersonaBean;
import java.awt.Window;
import java.text.Collator;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vPalomo
 */
public class ListadoPersonasAsignar extends javax.swing.JPanel {

    private boolean seleccionFila = false;
    //private ArrayList<PersonaBean> listaPersona; prueba
    
    private String idViaje;
    private String boton;//G-> Guardar  C->Cancelar
    private ArrayList<PersonaBean> listaPersonasSelec;
    private String tipoViajero;
    private String modoVentana;
    
    public static final String AsignarABus="AsignarABus";
    public static final String AsignarAViaje="AsignarAViaje";
    public static final String AsignarAHabitacion="AsignarAHabitacion";

    public String getModoVentana() {
        return modoVentana;
    }

    public String getTipoViajero() {
        return tipoViajero;
    }

    public ArrayList<PersonaBean> getListaPersonasSelec() {
        return listaPersonasSelec;
    }

    public String getBoton() {
        return boton;
    }

    public String getIdViaje() {
        return idViaje;
    }

    public void setIdViaje(String idViaje) {
        this.idViaje = idViaje;
    }
    
    
    /**
     * Genera la tabla para poder asignar personas que falta por asignar al viaje, al autobus o al alojamiento.
     * @param idViaje id del viaje a consultar
     * @param modoVentana AsignarABus AsignarAViaje AsignarAAlojamiento son los 3 posibles valores que puede tomar este campo.
     */
    public ListadoPersonasAsignar(String idViaje, String modoVentana) {
        this.idViaje=idViaje;
        this.modoVentana=modoVentana;
        initComponents();
        cargarListaPersonas();
        ponListenerTabla(jTablePersonas);
    }

    private void cargarListaPersonas() {
        ArrayList<PersonaBean> listaPersona=null;
        if(AsignarABus.equals(this.modoVentana)){
            listaPersona = GestionPersonasBD.getListaPersonasSinAutobus(idViaje);
        }else if(AsignarAViaje.equals(this.modoVentana)){
            listaPersona = GestionPersonasBD.getListaPersonasSinViaje(idViaje, true);
        }else if(AsignarAHabitacion.equals(this.modoVentana)){
            listaPersona = GestionPersonasBD.getListaPersonasSinHabitacion(idViaje);
        }
        listaPersona.sort(new Comparator<PersonaBean>() {
            @Override
            public int compare(PersonaBean p1, PersonaBean p2) {
                Collator c = Collator.getInstance(new Locale("es"));
                c.setStrength(Collator.PRIMARY);
                return c.compare(p1.getApellidos(), p2.getApellidos());
            }
        });
        //Primero se borra todo el contenido de la tabla
        DefaultTableModel datosTabla = (DefaultTableModel) jTablePersonas.getModel();
        for (int i = datosTabla.getRowCount(); i > 0; i--) {
            datosTabla.removeRow(i - 1);
        }
        listaPersona.forEach((persona) -> {
            datosTabla.addRow(new Object[]{
                false,
                persona.getApellidos(),
                persona.getNombre(),
                persona.getDNI(),
                persona.getIdPersona()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sel.", "Apellidos", "Nombre", "DNI", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePersonas);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(!seleccionFila){
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar al menos una persona");
            return;
        }
        DefaultTableModel datosTabla = (DefaultTableModel) jTablePersonas.getModel();
        listaPersonasSelec = new ArrayList<PersonaBean>();
        for (int i = 0; i < datosTabla.getRowCount(); i++) {
            if ((boolean) datosTabla.getValueAt(i, 0)) {
                PersonaBean persona = new PersonaBean();
                persona.setIdPersona((String) datosTabla.getValueAt(i, 4));
                persona.setNombre((String) datosTabla.getValueAt(i, 2));
                persona.setApellidos((String) datosTabla.getValueAt(i, 1));
                listaPersonasSelec.add(persona);
            }
        }
        if(listaPersonasSelec.size()<1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una persona");
            return;
        }
        if(ListadoPersonasAsignar.AsignarABus.equals(this.modoVentana)){
           boton="G";
        }else if(ListadoPersonasAsignar.AsignarAHabitacion.equals(this.modoVentana)){
           boton="G";
        }else if(ListadoPersonasAsignar.AsignarAViaje.equals(this.modoVentana)){
            JDialog frame = new JDialog((JFrame) null, "Guardar", true);
            frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
            OpcionesGuardarPersonaViajeModal ventana = new OpcionesGuardarPersonaViajeModal("2",GestionViajesBD.getViaje(idViaje).getNombre());
            frame.getContentPane().add(ventana);
            frame.pack();
            frame.setLocationRelativeTo(this);
            frame.setVisible(true);
            boton = ventana.getBoton();
            if("G".equalsIgnoreCase(boton)){
                tipoViajero = ventana.getTipoViajero();
                Window w = SwingUtilities.getWindowAncestor(this);
                w.setVisible(false);
            }
        }
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ponListenerTabla(JTable tabla) {
        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evento) {
                System.out.println("Seleccionado");
                seleccionFila = true;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    // End of variables declaration//GEN-END:variables
}
